<?php
/**
 * CoursesApi
 * PHP version 8.1
 *
 * @category Class
 * @package  LtiSaasApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LtiSaas API
 *
 * <p>A brief overview of the API versions:</p> <ul> <li><strong>v0:</strong> This version is solely for testing and does not interact with the database, nor does it involve any validation. It simply serves mock data.</li> <li><strong>v1:</strong> This is the official version of the LtiSaas API, intended for production use.</li> </ul> <p>Please be informed that when testing version v0, the HTTP <code>Access-Token</code> header should be set with the value 'dummy'.</p> <p>Also, please note that the API has a limit of 2500 results per response.</p> <p>Additionally, all webservices support both POST and GET requests. However, the POST method is required when uploading files.</p>
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LtiSaasApi\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use LtiSaasApi\ApiException;
use LtiSaasApi\Configuration;
use LtiSaasApi\FormDataProcessor;
use LtiSaasApi\HeaderSelector;
use LtiSaasApi\ObjectSerializer;

/**
 * CoursesApi Class Doc Comment
 *
 * @category Class
 * @package  LtiSaasApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CoursesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'courseAdd' => [
            'application/json',
        ],
        'courseDelete' => [
            'application/json',
        ],
        'courseGradeSet' => [
            'multipart/form-data',
        ],
        'courseList' => [
            'application/json',
        ],
        'courseUpdate' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation courseAdd
     *
     * Create a new course
     *
     * @param  string $coursename The name of the course to be created (required)
     * @param  string|null $coursenameshort The shortname of the course to be created (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseAdd'] to see the possible values for this operation
     *
     * @throws \LtiSaasApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LtiSaasApi\Model\CourseAdd200Response|\LtiSaasApi\Model\ErrorResponse|\LtiSaasApi\Model\ErrorResponse
     */
    public function courseAdd($coursename, $coursenameshort = null, string $contentType = self::contentTypes['courseAdd'][0])
    {
        list($response) = $this->courseAddWithHttpInfo($coursename, $coursenameshort, $contentType);
        return $response;
    }

    /**
     * Operation courseAddWithHttpInfo
     *
     * Create a new course
     *
     * @param  string $coursename The name of the course to be created (required)
     * @param  string|null $coursenameshort The shortname of the course to be created (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseAdd'] to see the possible values for this operation
     *
     * @throws \LtiSaasApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LtiSaasApi\Model\CourseAdd200Response|\LtiSaasApi\Model\ErrorResponse|\LtiSaasApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function courseAddWithHttpInfo($coursename, $coursenameshort = null, string $contentType = self::contentTypes['courseAdd'][0])
    {
        $request = $this->courseAddRequest($coursename, $coursenameshort, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\CourseAdd200Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LtiSaasApi\Model\CourseAdd200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\CourseAdd200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation courseAddAsync
     *
     * Create a new course
     *
     * @param  string $coursename The name of the course to be created (required)
     * @param  string|null $coursenameshort The shortname of the course to be created (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseAdd'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function courseAddAsync($coursename, $coursenameshort = null, string $contentType = self::contentTypes['courseAdd'][0])
    {
        return $this->courseAddAsyncWithHttpInfo($coursename, $coursenameshort, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation courseAddAsyncWithHttpInfo
     *
     * Create a new course
     *
     * @param  string $coursename The name of the course to be created (required)
     * @param  string|null $coursenameshort The shortname of the course to be created (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseAdd'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function courseAddAsyncWithHttpInfo($coursename, $coursenameshort = null, string $contentType = self::contentTypes['courseAdd'][0])
    {
        $returnType = '\LtiSaasApi\Model\CourseAdd200Response';
        $request = $this->courseAddRequest($coursename, $coursenameshort, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'courseAdd'
     *
     * @param  string $coursename The name of the course to be created (required)
     * @param  string|null $coursenameshort The shortname of the course to be created (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseAdd'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function courseAddRequest($coursename, $coursenameshort = null, string $contentType = self::contentTypes['courseAdd'][0])
    {

        // verify the required parameter 'coursename' is set
        if ($coursename === null || (is_array($coursename) && count($coursename) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $coursename when calling courseAdd'
            );
        }



        $resourcePath = '/course/add';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $coursename,
            'coursename', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $coursenameshort,
            'coursenameshort', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Access-Token');
        if ($apiKey !== null) {
            $headers['Access-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation courseDelete
     *
     * Delete an existing course by its ID
     *
     * @param  int $courseid The unique identifier of the course to be deleted (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseDelete'] to see the possible values for this operation
     *
     * @throws \LtiSaasApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LtiSaasApi\Model\CourseDelete200Response|\LtiSaasApi\Model\ErrorResponse|\LtiSaasApi\Model\ErrorResponse
     */
    public function courseDelete($courseid, string $contentType = self::contentTypes['courseDelete'][0])
    {
        list($response) = $this->courseDeleteWithHttpInfo($courseid, $contentType);
        return $response;
    }

    /**
     * Operation courseDeleteWithHttpInfo
     *
     * Delete an existing course by its ID
     *
     * @param  int $courseid The unique identifier of the course to be deleted (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseDelete'] to see the possible values for this operation
     *
     * @throws \LtiSaasApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LtiSaasApi\Model\CourseDelete200Response|\LtiSaasApi\Model\ErrorResponse|\LtiSaasApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function courseDeleteWithHttpInfo($courseid, string $contentType = self::contentTypes['courseDelete'][0])
    {
        $request = $this->courseDeleteRequest($courseid, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\CourseDelete200Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LtiSaasApi\Model\CourseDelete200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\CourseDelete200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation courseDeleteAsync
     *
     * Delete an existing course by its ID
     *
     * @param  int $courseid The unique identifier of the course to be deleted (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function courseDeleteAsync($courseid, string $contentType = self::contentTypes['courseDelete'][0])
    {
        return $this->courseDeleteAsyncWithHttpInfo($courseid, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation courseDeleteAsyncWithHttpInfo
     *
     * Delete an existing course by its ID
     *
     * @param  int $courseid The unique identifier of the course to be deleted (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function courseDeleteAsyncWithHttpInfo($courseid, string $contentType = self::contentTypes['courseDelete'][0])
    {
        $returnType = '\LtiSaasApi\Model\CourseDelete200Response';
        $request = $this->courseDeleteRequest($courseid, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'courseDelete'
     *
     * @param  int $courseid The unique identifier of the course to be deleted (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function courseDeleteRequest($courseid, string $contentType = self::contentTypes['courseDelete'][0])
    {

        // verify the required parameter 'courseid' is set
        if ($courseid === null || (is_array($courseid) && count($courseid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $courseid when calling courseDelete'
            );
        }


        $resourcePath = '/course/delete';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $courseid,
            'courseid', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Access-Token');
        if ($apiKey !== null) {
            $headers['Access-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation courseGradeSet
     *
     * Set or reset a user&#39;s course grade
     *
     * @param  int $userid Moodle user ID of the student (required)
     * @param  int $courseid Identifier of the course (required)
     * @param  float $grade Grade (required)
     * @param  int|null $reset If 1, resets the course grade to its original calculated value (removes override) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseGradeSet'] to see the possible values for this operation
     *
     * @throws \LtiSaasApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LtiSaasApi\Model\CourseGradeSet200Response|\LtiSaasApi\Model\CourseGradeSet400Response|\LtiSaasApi\Model\ErrorResponse
     */
    public function courseGradeSet($userid, $courseid, $grade, $reset = null, string $contentType = self::contentTypes['courseGradeSet'][0])
    {
        list($response) = $this->courseGradeSetWithHttpInfo($userid, $courseid, $grade, $reset, $contentType);
        return $response;
    }

    /**
     * Operation courseGradeSetWithHttpInfo
     *
     * Set or reset a user&#39;s course grade
     *
     * @param  int $userid Moodle user ID of the student (required)
     * @param  int $courseid Identifier of the course (required)
     * @param  float $grade Grade (required)
     * @param  int|null $reset If 1, resets the course grade to its original calculated value (removes override) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseGradeSet'] to see the possible values for this operation
     *
     * @throws \LtiSaasApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LtiSaasApi\Model\CourseGradeSet200Response|\LtiSaasApi\Model\CourseGradeSet400Response|\LtiSaasApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function courseGradeSetWithHttpInfo($userid, $courseid, $grade, $reset = null, string $contentType = self::contentTypes['courseGradeSet'][0])
    {
        $request = $this->courseGradeSetRequest($userid, $courseid, $grade, $reset, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\CourseGradeSet200Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\CourseGradeSet400Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LtiSaasApi\Model\CourseGradeSet200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\CourseGradeSet200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\CourseGradeSet400Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation courseGradeSetAsync
     *
     * Set or reset a user&#39;s course grade
     *
     * @param  int $userid Moodle user ID of the student (required)
     * @param  int $courseid Identifier of the course (required)
     * @param  float $grade Grade (required)
     * @param  int|null $reset If 1, resets the course grade to its original calculated value (removes override) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseGradeSet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function courseGradeSetAsync($userid, $courseid, $grade, $reset = null, string $contentType = self::contentTypes['courseGradeSet'][0])
    {
        return $this->courseGradeSetAsyncWithHttpInfo($userid, $courseid, $grade, $reset, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation courseGradeSetAsyncWithHttpInfo
     *
     * Set or reset a user&#39;s course grade
     *
     * @param  int $userid Moodle user ID of the student (required)
     * @param  int $courseid Identifier of the course (required)
     * @param  float $grade Grade (required)
     * @param  int|null $reset If 1, resets the course grade to its original calculated value (removes override) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseGradeSet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function courseGradeSetAsyncWithHttpInfo($userid, $courseid, $grade, $reset = null, string $contentType = self::contentTypes['courseGradeSet'][0])
    {
        $returnType = '\LtiSaasApi\Model\CourseGradeSet200Response';
        $request = $this->courseGradeSetRequest($userid, $courseid, $grade, $reset, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'courseGradeSet'
     *
     * @param  int $userid Moodle user ID of the student (required)
     * @param  int $courseid Identifier of the course (required)
     * @param  float $grade Grade (required)
     * @param  int|null $reset If 1, resets the course grade to its original calculated value (removes override) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseGradeSet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function courseGradeSetRequest($userid, $courseid, $grade, $reset = null, string $contentType = self::contentTypes['courseGradeSet'][0])
    {

        // verify the required parameter 'userid' is set
        if ($userid === null || (is_array($userid) && count($userid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $userid when calling courseGradeSet'
            );
        }

        // verify the required parameter 'courseid' is set
        if ($courseid === null || (is_array($courseid) && count($courseid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $courseid when calling courseGradeSet'
            );
        }

        // verify the required parameter 'grade' is set
        if ($grade === null || (is_array($grade) && count($grade) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $grade when calling courseGradeSet'
            );
        }
        if ($grade < 0) {
            throw new \InvalidArgumentException('invalid value for "$grade" when calling CoursesApi.courseGradeSet, must be bigger than or equal to 0.');
        }
        


        $resourcePath = '/course/grade';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;




        // form params
        $formDataProcessor = new FormDataProcessor();

        $formData = $formDataProcessor->prepare([
            'userid' => $userid,
            'courseid' => $courseid,
            'grade' => $grade,
            'reset' => $reset,
        ]);

        $formParams = $formDataProcessor->flatten($formData);
        $multipart = $formDataProcessor->has_file;

        $multipart = true;
        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Access-Token');
        if ($apiKey !== null) {
            $headers['Access-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation courseList
     *
     * Retrieve all courses
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseList'] to see the possible values for this operation
     *
     * @throws \LtiSaasApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LtiSaasApi\Model\CourseList200Response|\LtiSaasApi\Model\ErrorResponse|\LtiSaasApi\Model\ErrorResponse
     */
    public function courseList(string $contentType = self::contentTypes['courseList'][0])
    {
        list($response) = $this->courseListWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation courseListWithHttpInfo
     *
     * Retrieve all courses
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseList'] to see the possible values for this operation
     *
     * @throws \LtiSaasApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LtiSaasApi\Model\CourseList200Response|\LtiSaasApi\Model\ErrorResponse|\LtiSaasApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function courseListWithHttpInfo(string $contentType = self::contentTypes['courseList'][0])
    {
        $request = $this->courseListRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\CourseList200Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LtiSaasApi\Model\CourseList200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\CourseList200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation courseListAsync
     *
     * Retrieve all courses
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function courseListAsync(string $contentType = self::contentTypes['courseList'][0])
    {
        return $this->courseListAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation courseListAsyncWithHttpInfo
     *
     * Retrieve all courses
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function courseListAsyncWithHttpInfo(string $contentType = self::contentTypes['courseList'][0])
    {
        $returnType = '\LtiSaasApi\Model\CourseList200Response';
        $request = $this->courseListRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'courseList'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function courseListRequest(string $contentType = self::contentTypes['courseList'][0])
    {


        $resourcePath = '/course/list';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Access-Token');
        if ($apiKey !== null) {
            $headers['Access-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation courseUpdate
     *
     * Update an existing course
     *
     * @param  string $coursename The name of the course to be created (required)
     * @param  int $courseid The unique identifier of the course to be deleted (required)
     * @param  string|null $coursenameshort The name of the course to be created (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseUpdate'] to see the possible values for this operation
     *
     * @throws \LtiSaasApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LtiSaasApi\Model\CourseUpdate200Response|\LtiSaasApi\Model\ErrorResponse|\LtiSaasApi\Model\ErrorResponse
     */
    public function courseUpdate($coursename, $courseid, $coursenameshort = null, string $contentType = self::contentTypes['courseUpdate'][0])
    {
        list($response) = $this->courseUpdateWithHttpInfo($coursename, $courseid, $coursenameshort, $contentType);
        return $response;
    }

    /**
     * Operation courseUpdateWithHttpInfo
     *
     * Update an existing course
     *
     * @param  string $coursename The name of the course to be created (required)
     * @param  int $courseid The unique identifier of the course to be deleted (required)
     * @param  string|null $coursenameshort The name of the course to be created (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseUpdate'] to see the possible values for this operation
     *
     * @throws \LtiSaasApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LtiSaasApi\Model\CourseUpdate200Response|\LtiSaasApi\Model\ErrorResponse|\LtiSaasApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function courseUpdateWithHttpInfo($coursename, $courseid, $coursenameshort = null, string $contentType = self::contentTypes['courseUpdate'][0])
    {
        $request = $this->courseUpdateRequest($coursename, $courseid, $coursenameshort, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\CourseUpdate200Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LtiSaasApi\Model\CourseUpdate200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\CourseUpdate200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation courseUpdateAsync
     *
     * Update an existing course
     *
     * @param  string $coursename The name of the course to be created (required)
     * @param  int $courseid The unique identifier of the course to be deleted (required)
     * @param  string|null $coursenameshort The name of the course to be created (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function courseUpdateAsync($coursename, $courseid, $coursenameshort = null, string $contentType = self::contentTypes['courseUpdate'][0])
    {
        return $this->courseUpdateAsyncWithHttpInfo($coursename, $courseid, $coursenameshort, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation courseUpdateAsyncWithHttpInfo
     *
     * Update an existing course
     *
     * @param  string $coursename The name of the course to be created (required)
     * @param  int $courseid The unique identifier of the course to be deleted (required)
     * @param  string|null $coursenameshort The name of the course to be created (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function courseUpdateAsyncWithHttpInfo($coursename, $courseid, $coursenameshort = null, string $contentType = self::contentTypes['courseUpdate'][0])
    {
        $returnType = '\LtiSaasApi\Model\CourseUpdate200Response';
        $request = $this->courseUpdateRequest($coursename, $courseid, $coursenameshort, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'courseUpdate'
     *
     * @param  string $coursename The name of the course to be created (required)
     * @param  int $courseid The unique identifier of the course to be deleted (required)
     * @param  string|null $coursenameshort The name of the course to be created (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function courseUpdateRequest($coursename, $courseid, $coursenameshort = null, string $contentType = self::contentTypes['courseUpdate'][0])
    {

        // verify the required parameter 'coursename' is set
        if ($coursename === null || (is_array($coursename) && count($coursename) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $coursename when calling courseUpdate'
            );
        }

        // verify the required parameter 'courseid' is set
        if ($courseid === null || (is_array($courseid) && count($courseid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $courseid when calling courseUpdate'
            );
        }



        $resourcePath = '/course/update';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $coursename,
            'coursename', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $coursenameshort,
            'coursenameshort', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $courseid,
            'courseid', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Access-Token');
        if ($apiKey !== null) {
            $headers['Access-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
