<?php
/**
 * LTIAnalyticsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  LtiSaasApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LtiSaas API
 *
 * <p>A brief overview of the API versions:</p> <ul> <li><strong>v0:</strong> This version is solely for testing and does not interact with the database, nor does it involve any validation. It simply serves mock data.</li> <li><strong>v1:</strong> This is the official version of the LtiSaas API, intended for production use.</li> </ul> <p>Please be informed that when testing version v0, the HTTP <code>Access-Token</code> header should be set with the value 'dummy'.</p> <p>Also, please note that the API has a limit of 2500 results per response.</p> <p>Additionally, all webservices support both POST and GET requests. However, the POST method is required when uploading files.</p>
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.13.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LtiSaasApi\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use LtiSaasApi\ApiException;
use LtiSaasApi\Configuration;
use LtiSaasApi\FormDataProcessor;
use LtiSaasApi\HeaderSelector;
use LtiSaasApi\ObjectSerializer;

/**
 * LTIAnalyticsApi Class Doc Comment
 *
 * @category Class
 * @package  LtiSaasApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LTIAnalyticsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'courseLtiRegistrationsByDay' => [
            'application/json',
        ],
        'courseLtiRegistrationsSumByCourse' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation courseLtiRegistrationsByDay
     *
     * Get LTI registrations by day
     *
     * @param  \DateTime $from The start date (format: DD-MM-YYYY) (required)
     * @param  \DateTime $till The end date (format: DD-MM-YYYY) (required)
     * @param  int|null $toolid The identifier of the LTI tool (optional) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseLtiRegistrationsByDay'] to see the possible values for this operation
     *
     * @throws \LtiSaasApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LtiSaasApi\Model\CourseLtiRegistrationsByDay200Response|\LtiSaasApi\Model\ErrorResponse|\LtiSaasApi\Model\ErrorResponse
     */
    public function courseLtiRegistrationsByDay($from, $till, $toolid = null, string $contentType = self::contentTypes['courseLtiRegistrationsByDay'][0])
    {
        list($response) = $this->courseLtiRegistrationsByDayWithHttpInfo($from, $till, $toolid, $contentType);
        return $response;
    }

    /**
     * Operation courseLtiRegistrationsByDayWithHttpInfo
     *
     * Get LTI registrations by day
     *
     * @param  \DateTime $from The start date (format: DD-MM-YYYY) (required)
     * @param  \DateTime $till The end date (format: DD-MM-YYYY) (required)
     * @param  int|null $toolid The identifier of the LTI tool (optional) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseLtiRegistrationsByDay'] to see the possible values for this operation
     *
     * @throws \LtiSaasApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LtiSaasApi\Model\CourseLtiRegistrationsByDay200Response|\LtiSaasApi\Model\ErrorResponse|\LtiSaasApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function courseLtiRegistrationsByDayWithHttpInfo($from, $till, $toolid = null, string $contentType = self::contentTypes['courseLtiRegistrationsByDay'][0])
    {
        $request = $this->courseLtiRegistrationsByDayRequest($from, $till, $toolid, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\CourseLtiRegistrationsByDay200Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LtiSaasApi\Model\CourseLtiRegistrationsByDay200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\CourseLtiRegistrationsByDay200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation courseLtiRegistrationsByDayAsync
     *
     * Get LTI registrations by day
     *
     * @param  \DateTime $from The start date (format: DD-MM-YYYY) (required)
     * @param  \DateTime $till The end date (format: DD-MM-YYYY) (required)
     * @param  int|null $toolid The identifier of the LTI tool (optional) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseLtiRegistrationsByDay'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function courseLtiRegistrationsByDayAsync($from, $till, $toolid = null, string $contentType = self::contentTypes['courseLtiRegistrationsByDay'][0])
    {
        return $this->courseLtiRegistrationsByDayAsyncWithHttpInfo($from, $till, $toolid, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation courseLtiRegistrationsByDayAsyncWithHttpInfo
     *
     * Get LTI registrations by day
     *
     * @param  \DateTime $from The start date (format: DD-MM-YYYY) (required)
     * @param  \DateTime $till The end date (format: DD-MM-YYYY) (required)
     * @param  int|null $toolid The identifier of the LTI tool (optional) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseLtiRegistrationsByDay'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function courseLtiRegistrationsByDayAsyncWithHttpInfo($from, $till, $toolid = null, string $contentType = self::contentTypes['courseLtiRegistrationsByDay'][0])
    {
        $returnType = '\LtiSaasApi\Model\CourseLtiRegistrationsByDay200Response';
        $request = $this->courseLtiRegistrationsByDayRequest($from, $till, $toolid, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'courseLtiRegistrationsByDay'
     *
     * @param  \DateTime $from The start date (format: DD-MM-YYYY) (required)
     * @param  \DateTime $till The end date (format: DD-MM-YYYY) (required)
     * @param  int|null $toolid The identifier of the LTI tool (optional) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseLtiRegistrationsByDay'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function courseLtiRegistrationsByDayRequest($from, $till, $toolid = null, string $contentType = self::contentTypes['courseLtiRegistrationsByDay'][0])
    {

        // verify the required parameter 'from' is set
        if ($from === null || (is_array($from) && count($from) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $from when calling courseLtiRegistrationsByDay'
            );
        }

        // verify the required parameter 'till' is set
        if ($till === null || (is_array($till) && count($till) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $till when calling courseLtiRegistrationsByDay'
            );
        }



        $resourcePath = '/course/lti/registrations_by_day';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $from,
            'from', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $till,
            'till', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $toolid,
            'toolid', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Access-Token');
        if ($apiKey !== null) {
            $headers['Access-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation courseLtiRegistrationsSumByCourse
     *
     * Get total LTI registrations per course
     *
     * @param  \DateTime $from The start date (format: DD-MM-YYYY) (required)
     * @param  \DateTime $till The end date (format: DD-MM-YYYY) (required)
     * @param  int|null $courseid The identifier of the course (optional) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseLtiRegistrationsSumByCourse'] to see the possible values for this operation
     *
     * @throws \LtiSaasApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LtiSaasApi\Model\CourseLtiRegistrationsSumByCourse200Response|\LtiSaasApi\Model\ErrorResponse|\LtiSaasApi\Model\ErrorResponse
     */
    public function courseLtiRegistrationsSumByCourse($from, $till, $courseid = null, string $contentType = self::contentTypes['courseLtiRegistrationsSumByCourse'][0])
    {
        list($response) = $this->courseLtiRegistrationsSumByCourseWithHttpInfo($from, $till, $courseid, $contentType);
        return $response;
    }

    /**
     * Operation courseLtiRegistrationsSumByCourseWithHttpInfo
     *
     * Get total LTI registrations per course
     *
     * @param  \DateTime $from The start date (format: DD-MM-YYYY) (required)
     * @param  \DateTime $till The end date (format: DD-MM-YYYY) (required)
     * @param  int|null $courseid The identifier of the course (optional) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseLtiRegistrationsSumByCourse'] to see the possible values for this operation
     *
     * @throws \LtiSaasApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LtiSaasApi\Model\CourseLtiRegistrationsSumByCourse200Response|\LtiSaasApi\Model\ErrorResponse|\LtiSaasApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function courseLtiRegistrationsSumByCourseWithHttpInfo($from, $till, $courseid = null, string $contentType = self::contentTypes['courseLtiRegistrationsSumByCourse'][0])
    {
        $request = $this->courseLtiRegistrationsSumByCourseRequest($from, $till, $courseid, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\CourseLtiRegistrationsSumByCourse200Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LtiSaasApi\Model\CourseLtiRegistrationsSumByCourse200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\CourseLtiRegistrationsSumByCourse200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation courseLtiRegistrationsSumByCourseAsync
     *
     * Get total LTI registrations per course
     *
     * @param  \DateTime $from The start date (format: DD-MM-YYYY) (required)
     * @param  \DateTime $till The end date (format: DD-MM-YYYY) (required)
     * @param  int|null $courseid The identifier of the course (optional) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseLtiRegistrationsSumByCourse'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function courseLtiRegistrationsSumByCourseAsync($from, $till, $courseid = null, string $contentType = self::contentTypes['courseLtiRegistrationsSumByCourse'][0])
    {
        return $this->courseLtiRegistrationsSumByCourseAsyncWithHttpInfo($from, $till, $courseid, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation courseLtiRegistrationsSumByCourseAsyncWithHttpInfo
     *
     * Get total LTI registrations per course
     *
     * @param  \DateTime $from The start date (format: DD-MM-YYYY) (required)
     * @param  \DateTime $till The end date (format: DD-MM-YYYY) (required)
     * @param  int|null $courseid The identifier of the course (optional) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseLtiRegistrationsSumByCourse'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function courseLtiRegistrationsSumByCourseAsyncWithHttpInfo($from, $till, $courseid = null, string $contentType = self::contentTypes['courseLtiRegistrationsSumByCourse'][0])
    {
        $returnType = '\LtiSaasApi\Model\CourseLtiRegistrationsSumByCourse200Response';
        $request = $this->courseLtiRegistrationsSumByCourseRequest($from, $till, $courseid, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'courseLtiRegistrationsSumByCourse'
     *
     * @param  \DateTime $from The start date (format: DD-MM-YYYY) (required)
     * @param  \DateTime $till The end date (format: DD-MM-YYYY) (required)
     * @param  int|null $courseid The identifier of the course (optional) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseLtiRegistrationsSumByCourse'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function courseLtiRegistrationsSumByCourseRequest($from, $till, $courseid = null, string $contentType = self::contentTypes['courseLtiRegistrationsSumByCourse'][0])
    {

        // verify the required parameter 'from' is set
        if ($from === null || (is_array($from) && count($from) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $from when calling courseLtiRegistrationsSumByCourse'
            );
        }

        // verify the required parameter 'till' is set
        if ($till === null || (is_array($till) && count($till) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $till when calling courseLtiRegistrationsSumByCourse'
            );
        }



        $resourcePath = '/course/lti/registrations_sum_by_course';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $from,
            'from', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $till,
            'till', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $courseid,
            'courseid', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Access-Token');
        if ($apiKey !== null) {
            $headers['Access-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
