<?php
/**
 * LTIToolsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  LtiSaasApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LtiSaas API
 *
 * <p>A brief overview of the API versions:</p> <ul> <li><strong>v0:</strong> This version is solely for testing and does not interact with the database, nor does it involve any validation. It simply serves mock data.</li> <li><strong>v1:</strong> This is the official version of the LtiSaas API, intended for production use.</li> </ul> <p>Please be informed that when testing version v0, the HTTP <code>Access-Token</code> header should be set with the value 'dummy'.</p> <p>Also, please note that the API has a limit of 2500 results per response.</p> <p>Additionally, all webservices support both POST and GET requests. However, the POST method is required when uploading files.</p>
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace LtiSaasApi\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use LtiSaasApi\ApiException;
use LtiSaasApi\Configuration;
use LtiSaasApi\FormDataProcessor;
use LtiSaasApi\HeaderSelector;
use LtiSaasApi\ObjectSerializer;

/**
 * LTIToolsApi Class Doc Comment
 *
 * @category Class
 * @package  LtiSaasApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LTIToolsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'courseToolAdd' => [
            'application/json',
        ],
        'courseToolDelete' => [
            'application/json',
        ],
        'courseToolList' => [
            'application/json',
        ],
        'courseToolUpdate' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation courseToolAdd
     *
     * Add new tool to a course
     *
     * @param  int $courseid The ID of the course (required)
     * @param  string $ltiversion The version of LTI. Either LTI Advantage or Legacy LTI (required)
     * @param  string $name The name (required)
     * @param  string $publishmode The mode of publishing (course or activity) (required)
     * @param  int|null $learningobjectid The ID of the learning object. Only required if publishmode is set to activity (optional)
     * @param  int|null $maxenrolled The maximum enrollment. Defaults to unlimited (0). (optional)
     * @param  int|null $roleinstructor The role of the instructor. Defaults to 3 (optional)
     * @param  int|null $rolelearner The role of the learner. Defaults to 5 (optional)
     * @param  int|null $provisioningmodeinstructor The provisioning mode of the instructor. Defaults to 2 (optional)
     * @param  int|null $provisioningmodelearner The provisioning mode of the learner. Defaults to 1 (optional)
     * @param  int|null $gradesync Whether grade sync is enabled. Grade synchronization (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $gradesynccompletion Require course or activity completion prior to grade synchronisation (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $membersync Whether member sync is enabled. User synchronisation (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $membersyncmode User synchronisation mode (1&#x3D;Enrol new and unenrol missing users, 2&#x3D;Enrol new users, 3&#x3D;Unenrol missing      *          users) (optional)
     * @param  int|null $enrolperiod The duration of the enrolment (in seconds) (optional)
     * @param  \DateTime|null $enrolstartdate The enrolment start date (YYYY-MM-DDTHH:mm) (optional)
     * @param  \DateTime|null $enrolenddate The enrolment end date (YYYY-MM-DDTHH:mm) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseToolAdd'] to see the possible values for this operation
     *
     * @throws \LtiSaasApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LtiSaasApi\Model\CourseToolAdd200Response|\LtiSaasApi\Model\ErrorResponse|\LtiSaasApi\Model\ErrorResponse
     */
    public function courseToolAdd($courseid, $ltiversion, $name, $publishmode, $learningobjectid = null, $maxenrolled = null, $roleinstructor = null, $rolelearner = null, $provisioningmodeinstructor = null, $provisioningmodelearner = null, $gradesync = null, $gradesynccompletion = null, $membersync = null, $membersyncmode = null, $enrolperiod = null, $enrolstartdate = null, $enrolenddate = null, string $contentType = self::contentTypes['courseToolAdd'][0])
    {
        list($response) = $this->courseToolAddWithHttpInfo($courseid, $ltiversion, $name, $publishmode, $learningobjectid, $maxenrolled, $roleinstructor, $rolelearner, $provisioningmodeinstructor, $provisioningmodelearner, $gradesync, $gradesynccompletion, $membersync, $membersyncmode, $enrolperiod, $enrolstartdate, $enrolenddate, $contentType);
        return $response;
    }

    /**
     * Operation courseToolAddWithHttpInfo
     *
     * Add new tool to a course
     *
     * @param  int $courseid The ID of the course (required)
     * @param  string $ltiversion The version of LTI. Either LTI Advantage or Legacy LTI (required)
     * @param  string $name The name (required)
     * @param  string $publishmode The mode of publishing (course or activity) (required)
     * @param  int|null $learningobjectid The ID of the learning object. Only required if publishmode is set to activity (optional)
     * @param  int|null $maxenrolled The maximum enrollment. Defaults to unlimited (0). (optional)
     * @param  int|null $roleinstructor The role of the instructor. Defaults to 3 (optional)
     * @param  int|null $rolelearner The role of the learner. Defaults to 5 (optional)
     * @param  int|null $provisioningmodeinstructor The provisioning mode of the instructor. Defaults to 2 (optional)
     * @param  int|null $provisioningmodelearner The provisioning mode of the learner. Defaults to 1 (optional)
     * @param  int|null $gradesync Whether grade sync is enabled. Grade synchronization (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $gradesynccompletion Require course or activity completion prior to grade synchronisation (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $membersync Whether member sync is enabled. User synchronisation (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $membersyncmode User synchronisation mode (1&#x3D;Enrol new and unenrol missing users, 2&#x3D;Enrol new users, 3&#x3D;Unenrol missing      *          users) (optional)
     * @param  int|null $enrolperiod The duration of the enrolment (in seconds) (optional)
     * @param  \DateTime|null $enrolstartdate The enrolment start date (YYYY-MM-DDTHH:mm) (optional)
     * @param  \DateTime|null $enrolenddate The enrolment end date (YYYY-MM-DDTHH:mm) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseToolAdd'] to see the possible values for this operation
     *
     * @throws \LtiSaasApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LtiSaasApi\Model\CourseToolAdd200Response|\LtiSaasApi\Model\ErrorResponse|\LtiSaasApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function courseToolAddWithHttpInfo($courseid, $ltiversion, $name, $publishmode, $learningobjectid = null, $maxenrolled = null, $roleinstructor = null, $rolelearner = null, $provisioningmodeinstructor = null, $provisioningmodelearner = null, $gradesync = null, $gradesynccompletion = null, $membersync = null, $membersyncmode = null, $enrolperiod = null, $enrolstartdate = null, $enrolenddate = null, string $contentType = self::contentTypes['courseToolAdd'][0])
    {
        $request = $this->courseToolAddRequest($courseid, $ltiversion, $name, $publishmode, $learningobjectid, $maxenrolled, $roleinstructor, $rolelearner, $provisioningmodeinstructor, $provisioningmodelearner, $gradesync, $gradesynccompletion, $membersync, $membersyncmode, $enrolperiod, $enrolstartdate, $enrolenddate, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\CourseToolAdd200Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LtiSaasApi\Model\CourseToolAdd200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\CourseToolAdd200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation courseToolAddAsync
     *
     * Add new tool to a course
     *
     * @param  int $courseid The ID of the course (required)
     * @param  string $ltiversion The version of LTI. Either LTI Advantage or Legacy LTI (required)
     * @param  string $name The name (required)
     * @param  string $publishmode The mode of publishing (course or activity) (required)
     * @param  int|null $learningobjectid The ID of the learning object. Only required if publishmode is set to activity (optional)
     * @param  int|null $maxenrolled The maximum enrollment. Defaults to unlimited (0). (optional)
     * @param  int|null $roleinstructor The role of the instructor. Defaults to 3 (optional)
     * @param  int|null $rolelearner The role of the learner. Defaults to 5 (optional)
     * @param  int|null $provisioningmodeinstructor The provisioning mode of the instructor. Defaults to 2 (optional)
     * @param  int|null $provisioningmodelearner The provisioning mode of the learner. Defaults to 1 (optional)
     * @param  int|null $gradesync Whether grade sync is enabled. Grade synchronization (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $gradesynccompletion Require course or activity completion prior to grade synchronisation (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $membersync Whether member sync is enabled. User synchronisation (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $membersyncmode User synchronisation mode (1&#x3D;Enrol new and unenrol missing users, 2&#x3D;Enrol new users, 3&#x3D;Unenrol missing      *          users) (optional)
     * @param  int|null $enrolperiod The duration of the enrolment (in seconds) (optional)
     * @param  \DateTime|null $enrolstartdate The enrolment start date (YYYY-MM-DDTHH:mm) (optional)
     * @param  \DateTime|null $enrolenddate The enrolment end date (YYYY-MM-DDTHH:mm) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseToolAdd'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function courseToolAddAsync($courseid, $ltiversion, $name, $publishmode, $learningobjectid = null, $maxenrolled = null, $roleinstructor = null, $rolelearner = null, $provisioningmodeinstructor = null, $provisioningmodelearner = null, $gradesync = null, $gradesynccompletion = null, $membersync = null, $membersyncmode = null, $enrolperiod = null, $enrolstartdate = null, $enrolenddate = null, string $contentType = self::contentTypes['courseToolAdd'][0])
    {
        return $this->courseToolAddAsyncWithHttpInfo($courseid, $ltiversion, $name, $publishmode, $learningobjectid, $maxenrolled, $roleinstructor, $rolelearner, $provisioningmodeinstructor, $provisioningmodelearner, $gradesync, $gradesynccompletion, $membersync, $membersyncmode, $enrolperiod, $enrolstartdate, $enrolenddate, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation courseToolAddAsyncWithHttpInfo
     *
     * Add new tool to a course
     *
     * @param  int $courseid The ID of the course (required)
     * @param  string $ltiversion The version of LTI. Either LTI Advantage or Legacy LTI (required)
     * @param  string $name The name (required)
     * @param  string $publishmode The mode of publishing (course or activity) (required)
     * @param  int|null $learningobjectid The ID of the learning object. Only required if publishmode is set to activity (optional)
     * @param  int|null $maxenrolled The maximum enrollment. Defaults to unlimited (0). (optional)
     * @param  int|null $roleinstructor The role of the instructor. Defaults to 3 (optional)
     * @param  int|null $rolelearner The role of the learner. Defaults to 5 (optional)
     * @param  int|null $provisioningmodeinstructor The provisioning mode of the instructor. Defaults to 2 (optional)
     * @param  int|null $provisioningmodelearner The provisioning mode of the learner. Defaults to 1 (optional)
     * @param  int|null $gradesync Whether grade sync is enabled. Grade synchronization (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $gradesynccompletion Require course or activity completion prior to grade synchronisation (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $membersync Whether member sync is enabled. User synchronisation (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $membersyncmode User synchronisation mode (1&#x3D;Enrol new and unenrol missing users, 2&#x3D;Enrol new users, 3&#x3D;Unenrol missing      *          users) (optional)
     * @param  int|null $enrolperiod The duration of the enrolment (in seconds) (optional)
     * @param  \DateTime|null $enrolstartdate The enrolment start date (YYYY-MM-DDTHH:mm) (optional)
     * @param  \DateTime|null $enrolenddate The enrolment end date (YYYY-MM-DDTHH:mm) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseToolAdd'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function courseToolAddAsyncWithHttpInfo($courseid, $ltiversion, $name, $publishmode, $learningobjectid = null, $maxenrolled = null, $roleinstructor = null, $rolelearner = null, $provisioningmodeinstructor = null, $provisioningmodelearner = null, $gradesync = null, $gradesynccompletion = null, $membersync = null, $membersyncmode = null, $enrolperiod = null, $enrolstartdate = null, $enrolenddate = null, string $contentType = self::contentTypes['courseToolAdd'][0])
    {
        $returnType = '\LtiSaasApi\Model\CourseToolAdd200Response';
        $request = $this->courseToolAddRequest($courseid, $ltiversion, $name, $publishmode, $learningobjectid, $maxenrolled, $roleinstructor, $rolelearner, $provisioningmodeinstructor, $provisioningmodelearner, $gradesync, $gradesynccompletion, $membersync, $membersyncmode, $enrolperiod, $enrolstartdate, $enrolenddate, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'courseToolAdd'
     *
     * @param  int $courseid The ID of the course (required)
     * @param  string $ltiversion The version of LTI. Either LTI Advantage or Legacy LTI (required)
     * @param  string $name The name (required)
     * @param  string $publishmode The mode of publishing (course or activity) (required)
     * @param  int|null $learningobjectid The ID of the learning object. Only required if publishmode is set to activity (optional)
     * @param  int|null $maxenrolled The maximum enrollment. Defaults to unlimited (0). (optional)
     * @param  int|null $roleinstructor The role of the instructor. Defaults to 3 (optional)
     * @param  int|null $rolelearner The role of the learner. Defaults to 5 (optional)
     * @param  int|null $provisioningmodeinstructor The provisioning mode of the instructor. Defaults to 2 (optional)
     * @param  int|null $provisioningmodelearner The provisioning mode of the learner. Defaults to 1 (optional)
     * @param  int|null $gradesync Whether grade sync is enabled. Grade synchronization (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $gradesynccompletion Require course or activity completion prior to grade synchronisation (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $membersync Whether member sync is enabled. User synchronisation (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $membersyncmode User synchronisation mode (1&#x3D;Enrol new and unenrol missing users, 2&#x3D;Enrol new users, 3&#x3D;Unenrol missing      *          users) (optional)
     * @param  int|null $enrolperiod The duration of the enrolment (in seconds) (optional)
     * @param  \DateTime|null $enrolstartdate The enrolment start date (YYYY-MM-DDTHH:mm) (optional)
     * @param  \DateTime|null $enrolenddate The enrolment end date (YYYY-MM-DDTHH:mm) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseToolAdd'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function courseToolAddRequest($courseid, $ltiversion, $name, $publishmode, $learningobjectid = null, $maxenrolled = null, $roleinstructor = null, $rolelearner = null, $provisioningmodeinstructor = null, $provisioningmodelearner = null, $gradesync = null, $gradesynccompletion = null, $membersync = null, $membersyncmode = null, $enrolperiod = null, $enrolstartdate = null, $enrolenddate = null, string $contentType = self::contentTypes['courseToolAdd'][0])
    {

        // verify the required parameter 'courseid' is set
        if ($courseid === null || (is_array($courseid) && count($courseid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $courseid when calling courseToolAdd'
            );
        }

        // verify the required parameter 'ltiversion' is set
        if ($ltiversion === null || (is_array($ltiversion) && count($ltiversion) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ltiversion when calling courseToolAdd'
            );
        }

        // verify the required parameter 'name' is set
        if ($name === null || (is_array($name) && count($name) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $name when calling courseToolAdd'
            );
        }

        // verify the required parameter 'publishmode' is set
        if ($publishmode === null || (is_array($publishmode) && count($publishmode) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $publishmode when calling courseToolAdd'
            );
        }















        $resourcePath = '/course/tool/add';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $courseid,
            'courseid', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $ltiversion,
            'ltiversion', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $name,
            'name', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $publishmode,
            'publishmode', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $learningobjectid,
            'learningobjectid', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $maxenrolled,
            'maxenrolled', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $roleinstructor,
            'roleinstructor', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $rolelearner,
            'rolelearner', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $provisioningmodeinstructor,
            'provisioningmodeinstructor', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $provisioningmodelearner,
            'provisioningmodelearner', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $gradesync,
            'gradesync', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $gradesynccompletion,
            'gradesynccompletion', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $membersync,
            'membersync', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $membersyncmode,
            'membersyncmode', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $enrolperiod,
            'enrolperiod', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $enrolstartdate,
            'enrolstartdate', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $enrolenddate,
            'enrolenddate', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Access-Token');
        if ($apiKey !== null) {
            $headers['Access-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation courseToolDelete
     *
     * Delete a specific course tool
     *
     * @param  int $toolid The identifier of the lti tool (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseToolDelete'] to see the possible values for this operation
     *
     * @throws \LtiSaasApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LtiSaasApi\Model\CourseUpdate200Response|\LtiSaasApi\Model\ErrorResponse|\LtiSaasApi\Model\ErrorResponse
     */
    public function courseToolDelete($toolid, string $contentType = self::contentTypes['courseToolDelete'][0])
    {
        list($response) = $this->courseToolDeleteWithHttpInfo($toolid, $contentType);
        return $response;
    }

    /**
     * Operation courseToolDeleteWithHttpInfo
     *
     * Delete a specific course tool
     *
     * @param  int $toolid The identifier of the lti tool (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseToolDelete'] to see the possible values for this operation
     *
     * @throws \LtiSaasApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LtiSaasApi\Model\CourseUpdate200Response|\LtiSaasApi\Model\ErrorResponse|\LtiSaasApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function courseToolDeleteWithHttpInfo($toolid, string $contentType = self::contentTypes['courseToolDelete'][0])
    {
        $request = $this->courseToolDeleteRequest($toolid, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\CourseUpdate200Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LtiSaasApi\Model\CourseUpdate200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\CourseUpdate200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation courseToolDeleteAsync
     *
     * Delete a specific course tool
     *
     * @param  int $toolid The identifier of the lti tool (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseToolDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function courseToolDeleteAsync($toolid, string $contentType = self::contentTypes['courseToolDelete'][0])
    {
        return $this->courseToolDeleteAsyncWithHttpInfo($toolid, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation courseToolDeleteAsyncWithHttpInfo
     *
     * Delete a specific course tool
     *
     * @param  int $toolid The identifier of the lti tool (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseToolDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function courseToolDeleteAsyncWithHttpInfo($toolid, string $contentType = self::contentTypes['courseToolDelete'][0])
    {
        $returnType = '\LtiSaasApi\Model\CourseUpdate200Response';
        $request = $this->courseToolDeleteRequest($toolid, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'courseToolDelete'
     *
     * @param  int $toolid The identifier of the lti tool (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseToolDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function courseToolDeleteRequest($toolid, string $contentType = self::contentTypes['courseToolDelete'][0])
    {

        // verify the required parameter 'toolid' is set
        if ($toolid === null || (is_array($toolid) && count($toolid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $toolid when calling courseToolDelete'
            );
        }


        $resourcePath = '/course/tool/delete';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $toolid,
            'toolid', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Access-Token');
        if ($apiKey !== null) {
            $headers['Access-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation courseToolList
     *
     * List all LTI tools within a course
     *
     * @param  int $courseid The ID of the course (required)
     * @param  string|null $ltitype The version of LTI. Either LTI Advantage or Legacy LTI (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseToolList'] to see the possible values for this operation
     *
     * @throws \LtiSaasApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LtiSaasApi\Model\CourseToolList200Response|\LtiSaasApi\Model\ErrorResponse|\LtiSaasApi\Model\ErrorResponse
     */
    public function courseToolList($courseid, $ltitype = null, string $contentType = self::contentTypes['courseToolList'][0])
    {
        list($response) = $this->courseToolListWithHttpInfo($courseid, $ltitype, $contentType);
        return $response;
    }

    /**
     * Operation courseToolListWithHttpInfo
     *
     * List all LTI tools within a course
     *
     * @param  int $courseid The ID of the course (required)
     * @param  string|null $ltitype The version of LTI. Either LTI Advantage or Legacy LTI (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseToolList'] to see the possible values for this operation
     *
     * @throws \LtiSaasApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LtiSaasApi\Model\CourseToolList200Response|\LtiSaasApi\Model\ErrorResponse|\LtiSaasApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function courseToolListWithHttpInfo($courseid, $ltitype = null, string $contentType = self::contentTypes['courseToolList'][0])
    {
        $request = $this->courseToolListRequest($courseid, $ltitype, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\CourseToolList200Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LtiSaasApi\Model\CourseToolList200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\CourseToolList200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation courseToolListAsync
     *
     * List all LTI tools within a course
     *
     * @param  int $courseid The ID of the course (required)
     * @param  string|null $ltitype The version of LTI. Either LTI Advantage or Legacy LTI (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseToolList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function courseToolListAsync($courseid, $ltitype = null, string $contentType = self::contentTypes['courseToolList'][0])
    {
        return $this->courseToolListAsyncWithHttpInfo($courseid, $ltitype, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation courseToolListAsyncWithHttpInfo
     *
     * List all LTI tools within a course
     *
     * @param  int $courseid The ID of the course (required)
     * @param  string|null $ltitype The version of LTI. Either LTI Advantage or Legacy LTI (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseToolList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function courseToolListAsyncWithHttpInfo($courseid, $ltitype = null, string $contentType = self::contentTypes['courseToolList'][0])
    {
        $returnType = '\LtiSaasApi\Model\CourseToolList200Response';
        $request = $this->courseToolListRequest($courseid, $ltitype, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'courseToolList'
     *
     * @param  int $courseid The ID of the course (required)
     * @param  string|null $ltitype The version of LTI. Either LTI Advantage or Legacy LTI (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseToolList'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function courseToolListRequest($courseid, $ltitype = null, string $contentType = self::contentTypes['courseToolList'][0])
    {

        // verify the required parameter 'courseid' is set
        if ($courseid === null || (is_array($courseid) && count($courseid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $courseid when calling courseToolList'
            );
        }



        $resourcePath = '/course/tool/list';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $courseid,
            'courseid', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $ltitype,
            'ltitype', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Access-Token');
        if ($apiKey !== null) {
            $headers['Access-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation courseToolUpdate
     *
     * Update a specific course tool
     *
     * @param  int $toolid The ID of the lti tool (required)
     * @param  string|null $ltiversion The version of LTI (optional)
     * @param  string|null $name The name (optional)
     * @param  string|null $publishmode The mode of publishing (course or activity) (optional)
     * @param  int|null $learningobjectid The ID of the learning object. Only required if publishmode is set to activity (optional)
     * @param  int|null $maxenrolled The maximum enrollment (optional)
     * @param  int|null $roleinstructor The role of the instructor (optional)
     * @param  int|null $rolelearner The role of the learner (optional)
     * @param  int|null $provisioningmodeinstructor The provisioning mode of the instructor (optional)
     * @param  int|null $provisioningmodelearner The provisioning mode of the learner (optional)
     * @param  int|null $gradesync Whether grade sync is enabled. Grade synchronization (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $gradesynccompletion Require course or activity completion prior to grade synchronisation (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $membersync Whether member sync is enabled. User synchronisation (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $membersyncmode User synchronisation mode (1&#x3D;Enrol new and unenrol missing users, 2&#x3D;Enrol new users, 3&#x3D;Unenrol      *           missing users) (optional)
     * @param  int|null $enrolperiod The duration of the enrolment (in seconds) (optional)
     * @param  \DateTime|null $enrolstartdate The enrolment start date (YYYY-MM-DDTHH:mm) (optional)
     * @param  \DateTime|null $enrolenddate The enrolment end date (YYYY-MM-DDTHH:mm) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseToolUpdate'] to see the possible values for this operation
     *
     * @throws \LtiSaasApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \LtiSaasApi\Model\CourseToolAdd200Response|\LtiSaasApi\Model\ErrorResponse|\LtiSaasApi\Model\ErrorResponse
     */
    public function courseToolUpdate($toolid, $ltiversion = null, $name = null, $publishmode = null, $learningobjectid = null, $maxenrolled = null, $roleinstructor = null, $rolelearner = null, $provisioningmodeinstructor = null, $provisioningmodelearner = null, $gradesync = null, $gradesynccompletion = null, $membersync = null, $membersyncmode = null, $enrolperiod = null, $enrolstartdate = null, $enrolenddate = null, string $contentType = self::contentTypes['courseToolUpdate'][0])
    {
        list($response) = $this->courseToolUpdateWithHttpInfo($toolid, $ltiversion, $name, $publishmode, $learningobjectid, $maxenrolled, $roleinstructor, $rolelearner, $provisioningmodeinstructor, $provisioningmodelearner, $gradesync, $gradesynccompletion, $membersync, $membersyncmode, $enrolperiod, $enrolstartdate, $enrolenddate, $contentType);
        return $response;
    }

    /**
     * Operation courseToolUpdateWithHttpInfo
     *
     * Update a specific course tool
     *
     * @param  int $toolid The ID of the lti tool (required)
     * @param  string|null $ltiversion The version of LTI (optional)
     * @param  string|null $name The name (optional)
     * @param  string|null $publishmode The mode of publishing (course or activity) (optional)
     * @param  int|null $learningobjectid The ID of the learning object. Only required if publishmode is set to activity (optional)
     * @param  int|null $maxenrolled The maximum enrollment (optional)
     * @param  int|null $roleinstructor The role of the instructor (optional)
     * @param  int|null $rolelearner The role of the learner (optional)
     * @param  int|null $provisioningmodeinstructor The provisioning mode of the instructor (optional)
     * @param  int|null $provisioningmodelearner The provisioning mode of the learner (optional)
     * @param  int|null $gradesync Whether grade sync is enabled. Grade synchronization (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $gradesynccompletion Require course or activity completion prior to grade synchronisation (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $membersync Whether member sync is enabled. User synchronisation (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $membersyncmode User synchronisation mode (1&#x3D;Enrol new and unenrol missing users, 2&#x3D;Enrol new users, 3&#x3D;Unenrol      *           missing users) (optional)
     * @param  int|null $enrolperiod The duration of the enrolment (in seconds) (optional)
     * @param  \DateTime|null $enrolstartdate The enrolment start date (YYYY-MM-DDTHH:mm) (optional)
     * @param  \DateTime|null $enrolenddate The enrolment end date (YYYY-MM-DDTHH:mm) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseToolUpdate'] to see the possible values for this operation
     *
     * @throws \LtiSaasApi\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \LtiSaasApi\Model\CourseToolAdd200Response|\LtiSaasApi\Model\ErrorResponse|\LtiSaasApi\Model\ErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function courseToolUpdateWithHttpInfo($toolid, $ltiversion = null, $name = null, $publishmode = null, $learningobjectid = null, $maxenrolled = null, $roleinstructor = null, $rolelearner = null, $provisioningmodeinstructor = null, $provisioningmodelearner = null, $gradesync = null, $gradesynccompletion = null, $membersync = null, $membersyncmode = null, $enrolperiod = null, $enrolstartdate = null, $enrolenddate = null, string $contentType = self::contentTypes['courseToolUpdate'][0])
    {
        $request = $this->courseToolUpdateRequest($toolid, $ltiversion, $name, $publishmode, $learningobjectid, $maxenrolled, $roleinstructor, $rolelearner, $provisioningmodeinstructor, $provisioningmodelearner, $gradesync, $gradesynccompletion, $membersync, $membersyncmode, $enrolperiod, $enrolstartdate, $enrolenddate, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\CourseToolAdd200Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\ErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\LtiSaasApi\Model\ErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\LtiSaasApi\Model\CourseToolAdd200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\CourseToolAdd200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\LtiSaasApi\Model\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation courseToolUpdateAsync
     *
     * Update a specific course tool
     *
     * @param  int $toolid The ID of the lti tool (required)
     * @param  string|null $ltiversion The version of LTI (optional)
     * @param  string|null $name The name (optional)
     * @param  string|null $publishmode The mode of publishing (course or activity) (optional)
     * @param  int|null $learningobjectid The ID of the learning object. Only required if publishmode is set to activity (optional)
     * @param  int|null $maxenrolled The maximum enrollment (optional)
     * @param  int|null $roleinstructor The role of the instructor (optional)
     * @param  int|null $rolelearner The role of the learner (optional)
     * @param  int|null $provisioningmodeinstructor The provisioning mode of the instructor (optional)
     * @param  int|null $provisioningmodelearner The provisioning mode of the learner (optional)
     * @param  int|null $gradesync Whether grade sync is enabled. Grade synchronization (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $gradesynccompletion Require course or activity completion prior to grade synchronisation (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $membersync Whether member sync is enabled. User synchronisation (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $membersyncmode User synchronisation mode (1&#x3D;Enrol new and unenrol missing users, 2&#x3D;Enrol new users, 3&#x3D;Unenrol      *           missing users) (optional)
     * @param  int|null $enrolperiod The duration of the enrolment (in seconds) (optional)
     * @param  \DateTime|null $enrolstartdate The enrolment start date (YYYY-MM-DDTHH:mm) (optional)
     * @param  \DateTime|null $enrolenddate The enrolment end date (YYYY-MM-DDTHH:mm) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseToolUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function courseToolUpdateAsync($toolid, $ltiversion = null, $name = null, $publishmode = null, $learningobjectid = null, $maxenrolled = null, $roleinstructor = null, $rolelearner = null, $provisioningmodeinstructor = null, $provisioningmodelearner = null, $gradesync = null, $gradesynccompletion = null, $membersync = null, $membersyncmode = null, $enrolperiod = null, $enrolstartdate = null, $enrolenddate = null, string $contentType = self::contentTypes['courseToolUpdate'][0])
    {
        return $this->courseToolUpdateAsyncWithHttpInfo($toolid, $ltiversion, $name, $publishmode, $learningobjectid, $maxenrolled, $roleinstructor, $rolelearner, $provisioningmodeinstructor, $provisioningmodelearner, $gradesync, $gradesynccompletion, $membersync, $membersyncmode, $enrolperiod, $enrolstartdate, $enrolenddate, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation courseToolUpdateAsyncWithHttpInfo
     *
     * Update a specific course tool
     *
     * @param  int $toolid The ID of the lti tool (required)
     * @param  string|null $ltiversion The version of LTI (optional)
     * @param  string|null $name The name (optional)
     * @param  string|null $publishmode The mode of publishing (course or activity) (optional)
     * @param  int|null $learningobjectid The ID of the learning object. Only required if publishmode is set to activity (optional)
     * @param  int|null $maxenrolled The maximum enrollment (optional)
     * @param  int|null $roleinstructor The role of the instructor (optional)
     * @param  int|null $rolelearner The role of the learner (optional)
     * @param  int|null $provisioningmodeinstructor The provisioning mode of the instructor (optional)
     * @param  int|null $provisioningmodelearner The provisioning mode of the learner (optional)
     * @param  int|null $gradesync Whether grade sync is enabled. Grade synchronization (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $gradesynccompletion Require course or activity completion prior to grade synchronisation (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $membersync Whether member sync is enabled. User synchronisation (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $membersyncmode User synchronisation mode (1&#x3D;Enrol new and unenrol missing users, 2&#x3D;Enrol new users, 3&#x3D;Unenrol      *           missing users) (optional)
     * @param  int|null $enrolperiod The duration of the enrolment (in seconds) (optional)
     * @param  \DateTime|null $enrolstartdate The enrolment start date (YYYY-MM-DDTHH:mm) (optional)
     * @param  \DateTime|null $enrolenddate The enrolment end date (YYYY-MM-DDTHH:mm) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseToolUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function courseToolUpdateAsyncWithHttpInfo($toolid, $ltiversion = null, $name = null, $publishmode = null, $learningobjectid = null, $maxenrolled = null, $roleinstructor = null, $rolelearner = null, $provisioningmodeinstructor = null, $provisioningmodelearner = null, $gradesync = null, $gradesynccompletion = null, $membersync = null, $membersyncmode = null, $enrolperiod = null, $enrolstartdate = null, $enrolenddate = null, string $contentType = self::contentTypes['courseToolUpdate'][0])
    {
        $returnType = '\LtiSaasApi\Model\CourseToolAdd200Response';
        $request = $this->courseToolUpdateRequest($toolid, $ltiversion, $name, $publishmode, $learningobjectid, $maxenrolled, $roleinstructor, $rolelearner, $provisioningmodeinstructor, $provisioningmodelearner, $gradesync, $gradesynccompletion, $membersync, $membersyncmode, $enrolperiod, $enrolstartdate, $enrolenddate, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'courseToolUpdate'
     *
     * @param  int $toolid The ID of the lti tool (required)
     * @param  string|null $ltiversion The version of LTI (optional)
     * @param  string|null $name The name (optional)
     * @param  string|null $publishmode The mode of publishing (course or activity) (optional)
     * @param  int|null $learningobjectid The ID of the learning object. Only required if publishmode is set to activity (optional)
     * @param  int|null $maxenrolled The maximum enrollment (optional)
     * @param  int|null $roleinstructor The role of the instructor (optional)
     * @param  int|null $rolelearner The role of the learner (optional)
     * @param  int|null $provisioningmodeinstructor The provisioning mode of the instructor (optional)
     * @param  int|null $provisioningmodelearner The provisioning mode of the learner (optional)
     * @param  int|null $gradesync Whether grade sync is enabled. Grade synchronization (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $gradesynccompletion Require course or activity completion prior to grade synchronisation (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $membersync Whether member sync is enabled. User synchronisation (1&#x3D;Yes, 0&#x3D;No) (optional)
     * @param  int|null $membersyncmode User synchronisation mode (1&#x3D;Enrol new and unenrol missing users, 2&#x3D;Enrol new users, 3&#x3D;Unenrol      *           missing users) (optional)
     * @param  int|null $enrolperiod The duration of the enrolment (in seconds) (optional)
     * @param  \DateTime|null $enrolstartdate The enrolment start date (YYYY-MM-DDTHH:mm) (optional)
     * @param  \DateTime|null $enrolenddate The enrolment end date (YYYY-MM-DDTHH:mm) (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['courseToolUpdate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function courseToolUpdateRequest($toolid, $ltiversion = null, $name = null, $publishmode = null, $learningobjectid = null, $maxenrolled = null, $roleinstructor = null, $rolelearner = null, $provisioningmodeinstructor = null, $provisioningmodelearner = null, $gradesync = null, $gradesynccompletion = null, $membersync = null, $membersyncmode = null, $enrolperiod = null, $enrolstartdate = null, $enrolenddate = null, string $contentType = self::contentTypes['courseToolUpdate'][0])
    {

        // verify the required parameter 'toolid' is set
        if ($toolid === null || (is_array($toolid) && count($toolid) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $toolid when calling courseToolUpdate'
            );
        }


















        $resourcePath = '/course/tool/update';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $toolid,
            'toolid', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $ltiversion,
            'ltiversion', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $name,
            'name', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $publishmode,
            'publishmode', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $learningobjectid,
            'learningobjectid', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $maxenrolled,
            'maxenrolled', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $roleinstructor,
            'roleinstructor', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $rolelearner,
            'rolelearner', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $provisioningmodeinstructor,
            'provisioningmodeinstructor', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $provisioningmodelearner,
            'provisioningmodelearner', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $gradesync,
            'gradesync', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $gradesynccompletion,
            'gradesynccompletion', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $membersync,
            'membersync', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $membersyncmode,
            'membersyncmode', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $enrolperiod,
            'enrolperiod', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $enrolstartdate,
            'enrolstartdate', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $enrolenddate,
            'enrolenddate', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Access-Token');
        if ($apiKey !== null) {
            $headers['Access-Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
