<?php
/**
 * CourseLtiRegistrationsSumByCourse200ResponseResultsInnerTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  LtiSaasApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LtiSaas API
 *
 * <p>A brief overview of the API versions:</p> <ul> <li><strong>v0:</strong> This version is solely for testing and does not interact with the database, nor does it involve any validation. It simply serves mock data.</li> <li><strong>v1:</strong> This is the official version of the LtiSaas API, intended for production use.</li> </ul> <p>Please be informed that when testing version v0, the HTTP <code>Access-Token</code> header should be set with the value 'dummy'.</p> <p>Also, please note that the API has a limit of 2500 results per response.</p> <p>Additionally, all webservices support both POST and GET requests. However, the POST method is required when uploading files.</p>
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace LtiSaasApi\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CourseLtiRegistrationsSumByCourse200ResponseResultsInnerTest Class Doc Comment
 *
 * @category    Class
 * @description CourseLtiRegistrationsSumByCourse200ResponseResultsInner
 * @package     LtiSaasApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CourseLtiRegistrationsSumByCourse200ResponseResultsInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CourseLtiRegistrationsSumByCourse200ResponseResultsInner"
     */
    public function testCourseLtiRegistrationsSumByCourse200ResponseResultsInner()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "totalregistrations"
     */
    public function testPropertyTotalregistrations()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "courseid"
     */
    public function testPropertyCourseid()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "coursename"
     */
    public function testPropertyCoursename()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "coursenameshort"
     */
    public function testPropertyCoursenameshort()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
