<?php
/**
 * InlineResponse2007ResultsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * LtiSaas API
 *
 * The LtiSaas API version 0 serves mock data for testing purposes. It requires no authorization, making it ideal for development and testing.
 *
 * OpenAPI spec version: 0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse2007ResultsTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse2007Results
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse2007ResultsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse2007Results"
     */
    public function testInlineResponse2007Results()
    {
    }

    /**
     * Test attribute "userid"
     */
    public function testPropertyUserid()
    {
    }

    /**
     * Test attribute "firstname"
     */
    public function testPropertyFirstname()
    {
    }

    /**
     * Test attribute "lastname"
     */
    public function testPropertyLastname()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "lastip"
     */
    public function testPropertyLastip()
    {
    }

    /**
     * Test attribute "lti_lastgrade"
     */
    public function testPropertyLtiLastgrade()
    {
    }

    /**
     * Test attribute "lti_lastaccess"
     */
    public function testPropertyLtiLastaccess()
    {
    }

    /**
     * Test attribute "lti_timecreated"
     */
    public function testPropertyLtiTimecreated()
    {
    }
}
