<?php
/**
 * InlineResponse200ResultsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * LtiSaas API
 *
 * The LtiSaas API version 0 serves mock data for testing purposes. It requires no authorization, making it ideal for development and testing.
 *
 * OpenAPI spec version: 0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * InlineResponse200ResultsTest Class Doc Comment
 *
 * @category    Class
 * @description InlineResponse200Results
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InlineResponse200ResultsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "InlineResponse200Results"
     */
    public function testInlineResponse200Results()
    {
    }

    /**
     * Test attribute "totalregistrations"
     */
    public function testPropertyTotalregistrations()
    {
    }

    /**
     * Test attribute "totalltitools"
     */
    public function testPropertyTotalltitools()
    {
    }

    /**
     * Test attribute "courseid"
     */
    public function testPropertyCourseid()
    {
    }

    /**
     * Test attribute "toolids"
     */
    public function testPropertyToolids()
    {
    }

    /**
     * Test attribute "coursename"
     */
    public function testPropertyCoursename()
    {
    }

    /**
     * Test attribute "lastaccess"
     */
    public function testPropertyLastaccess()
    {
    }
}
