<?php
/**
 * ScromUpdateBodyTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  LtiSaasApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * LtiSaas API
 *
 * <p>A brief overview of the API versions:</p> <ul> <li><strong>v0:</strong> This version is solely for testing and does not interact with the database, nor does it involve any validation. It simply serves mock data.</li> <li><strong>v1:</strong> This is the official version of the LtiSaas API, intended for production use.</li> </ul> <p>Please be informed that when testing version v0, the HTTP <code>Access-Token</code> header should be set with the value 'dummy'.</p> <p>Also, please note that the API has a limit of 2500 results per response.</p> <p>Additionally, all webservices support both POST and GET requests. However, the POST method is required when uploading files.</p>
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace LtiSaasApi;

use PHPUnit\Framework\TestCase;

/**
 * ScromUpdateBodyTest Class Doc Comment
 *
 * @category    Class
 * @description ScromUpdateBody
 * @package     LtiSaasApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ScromUpdateBodyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ScromUpdateBody"
     */
    public function testScromUpdateBody()
    {
    }

    /**
     * Test attribute "learningobjectid"
     */
    public function testPropertyLearningobjectid()
    {
    }

    /**
     * Test attribute "packagefile"
     */
    public function testPropertyPackagefile()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "popup"
     */
    public function testPropertyPopup()
    {
    }

    /**
     * Test attribute "width"
     */
    public function testPropertyWidth()
    {
    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {
    }

    /**
     * Test attribute "grademethod"
     */
    public function testPropertyGrademethod()
    {
    }

    /**
     * Test attribute "maxgrade"
     */
    public function testPropertyMaxgrade()
    {
    }

    /**
     * Test attribute "maxattempt"
     */
    public function testPropertyMaxattempt()
    {
    }

    /**
     * Test attribute "whatgrade"
     */
    public function testPropertyWhatgrade()
    {
    }

    /**
     * Test attribute "forcenewattempt"
     */
    public function testPropertyForcenewattempt()
    {
    }

    /**
     * Test attribute "lastattemptlock"
     */
    public function testPropertyLastattemptlock()
    {
    }

    /**
     * Test attribute "autocommit"
     */
    public function testPropertyAutocommit()
    {
    }

    /**
     * Test attribute "masteryoverride"
     */
    public function testPropertyMasteryoverride()
    {
    }
}
