<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * LtiSaas API
 *
 * API versions description:  *     - v0: For testing purposes only. It serves mock data that won't be written to the database and there is no validation.  *     - v1: The official version of the LtiSaas API.  *     Note: For testing v0, use the HTTP `Access-Token` header with the value 'dummy'
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.46
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for courseAdd
     *
     * Create a new course.
     *
     */
    public function testCourseAdd()
    {
    }

    /**
     * Test case for courseDelete
     *
     * Delete an existing course by its ID.
     *
     */
    public function testCourseDelete()
    {
    }

    /**
     * Test case for courseLearningObjectDelete
     *
     * Delete a specific learning object.
     *
     */
    public function testCourseLearningObjectDelete()
    {
    }

    /**
     * Test case for courseLearningObjectScromAdd
     *
     * Add an SCORM package to a course.
     *
     */
    public function testCourseLearningObjectScromAdd()
    {
    }

    /**
     * Test case for courseLearningobjectList
     *
     * Get learning objects for a course.
     *
     */
    public function testCourseLearningobjectList()
    {
    }

    /**
     * Test case for courseLearningobjectScormUpdate
     *
     * Update SCORM Learning Object.
     *
     */
    public function testCourseLearningobjectScormUpdate()
    {
    }

    /**
     * Test case for courseList
     *
     * Retrieve all courses.
     *
     */
    public function testCourseList()
    {
    }

    /**
     * Test case for courseLtiRegistrationsByDay
     *
     * Get LTI registrations by day.
     *
     */
    public function testCourseLtiRegistrationsByDay()
    {
    }

    /**
     * Test case for courseLtiRegistrationsSumByCourse
     *
     * Get total LTI registrations per course.
     *
     */
    public function testCourseLtiRegistrationsSumByCourse()
    {
    }

    /**
     * Test case for courseToolAdd
     *
     * Add new tool to a course.
     *
     */
    public function testCourseToolAdd()
    {
    }

    /**
     * Test case for courseToolDelete
     *
     * Delete a specific course tool.
     *
     */
    public function testCourseToolDelete()
    {
    }

    /**
     * Test case for courseToolUpdate
     *
     * Update a specific course tool.
     *
     */
    public function testCourseToolUpdate()
    {
    }

    /**
     * Test case for tokenAdd
     *
     * Add a new API token.
     *
     */
    public function testTokenAdd()
    {
    }

    /**
     * Test case for tokenDelete
     *
     * Delete an API token.
     *
     */
    public function testTokenDelete()
    {
    }

    /**
     * Test case for tokenList
     *
     * Get list of API tokens.
     *
     */
    public function testTokenList()
    {
    }

    /**
     * Test case for userDelete
     *
     * Delete a user by ID.
     *
     */
    public function testUserDelete()
    {
    }

    /**
     * Test case for userDeleteBulk
     *
     * Delete multiple users by IDs.
     *
     */
    public function testUserDeleteBulk()
    {
    }

    /**
     * Test case for userList
     *
     * Get list of users in a tool.
     *
     */
    public function testUserList()
    {
    }
}
