<?php
/**
 * DefaultApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  LtiSaasApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * LtiSaas API
 *
 * <p>A brief overview of the API versions:</p> <ul> <li><strong>v0:</strong> This version is solely for testing and does not interact with the database, nor does it involve any validation. It simply serves mock data.</li> <li><strong>v1:</strong> This is the official version of the LtiSaas API, intended for production use.</li> </ul> <p>Please be informed that when testing version v0, the HTTP <code>Access-Token</code> header should be set with the value 'dummy'.</p> <p>Also, please note that the API has a limit of 2500 results per response.</p> <p>Additionally, all webservices support both POST and GET requests. However, the POST method is required when uploading files.</p>
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace LtiSaasApi\Test\Api;

use \LtiSaasApi\Configuration;
use \LtiSaasApi\ApiException;
use \LtiSaasApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  LtiSaasApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefaultApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for courseAdd
     *
     * Create a new course.
     *
     */
    public function testCourseAdd()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for courseDelete
     *
     * Delete an existing course by its ID.
     *
     */
    public function testCourseDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for courseLearningObjectDelete
     *
     * Delete a specific learning object.
     *
     */
    public function testCourseLearningObjectDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for courseLearningObjectScromAdd
     *
     * Add an SCORM package to a course.
     *
     */
    public function testCourseLearningObjectScromAdd()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for courseLearningobjectList
     *
     * Get learning objects for a course.
     *
     */
    public function testCourseLearningobjectList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for courseLearningobjectScormUpdate
     *
     * Update SCORM Learning Object.
     *
     */
    public function testCourseLearningobjectScormUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for courseList
     *
     * Retrieve all courses.
     *
     */
    public function testCourseList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for courseLtiRegistrationsByDay
     *
     * Get LTI registrations by day.
     *
     */
    public function testCourseLtiRegistrationsByDay()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for courseLtiRegistrationsSumByCourse
     *
     * Get total LTI registrations per course.
     *
     */
    public function testCourseLtiRegistrationsSumByCourse()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for courseToolAdd
     *
     * Add new tool to a course.
     *
     */
    public function testCourseToolAdd()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for courseToolDelete
     *
     * Delete a specific course tool.
     *
     */
    public function testCourseToolDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for courseToolList
     *
     * List all LTI tools within a course.
     *
     */
    public function testCourseToolList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for courseToolUpdate
     *
     * Update a specific course tool.
     *
     */
    public function testCourseToolUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for courseUpdate
     *
     * Update an existing course.
     *
     */
    public function testCourseUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for tokenAdd
     *
     * Add a new API token.
     *
     */
    public function testTokenAdd()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for tokenDelete
     *
     * Delete an API token.
     *
     */
    public function testTokenDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for tokenList
     *
     * Get list of API tokens.
     *
     */
    public function testTokenList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userDelete
     *
     * Delete a user by ID.
     *
     */
    public function testUserDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userDeleteBulk
     *
     * Delete multiple users by IDs.
     *
     */
    public function testUserDeleteBulk()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for userList
     *
     * Get list of users in a tool.
     *
     */
    public function testUserList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
